# Generated by Django 5.1.3 on 2024-11-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
