# Generated by Django 5.1.3 on 2024-11-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0002_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={
                "ordering": ["first_name", "last_name", "username"],
                "verbose_name_plural": "cooks",
            },
        ),
    ]
