# Generated by Django 5.1.3 on 2024-11-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0003_alter_cook_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={"verbose_name_plural": "cook"},
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={"verbose_name_plural": "dish"},
        ),
    ]
